Print error message

diff --git a/.github/workflows/tf-deploy.yml b/.github/workflows/tf-deploy.yml
--- a/.github/workflows/tf-deploy.yml
+++ b/.github/workflows/tf-deploy.yml
@@ -51,6 +51,11 @@ jobs:
             refs/heads/cmn)
               echo 'KEEP_APP_ENV=cmn' >> $GITHUB_ENV
             ;;
+            *)
+              echo 'ERR: Cannot determine env by git ref'
+              echo "ERR: Ref - ${{github.ref}}"
+              exit 22
+            ;;
           esac
 
       - name: Terraform Init
